---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
      - args:
        - -text=hello
        - -listen=:3000
        image: hashicorp/http-echo:1.0
        name: echo
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
  - name: echo
    port: 3000
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo.local
spec:
  ingressClassName: nginx
  rules:
  - host: echo.local
    http:
      paths:
      - backend:
          service:
            name: echo
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
